"""
UNIVERSAL POSITION REGISTRY
Tracks ALL open positions regardless of source (autonomous, manual LLM prompt, webhook, etc)
Provides unified interface for portfolio management across clones
"""

import json
import time
from datetime import datetime
from typing import Dict, List, Optional, Tuple
from dataclasses import dataclass, field, asdict
from enum import Enum
import threading
from pathlib import Path
import hashlib

class PositionSource(Enum):
    """Where did this position come from?"""
    AUTONOMOUS = "autonomous"  # Auto-generated by system
    MANUAL_PROMPT = "manual_prompt"  # User/LLM command via prompt
    WEBHOOK = "webhook"  # External webhook trigger
    COPY_TRADE = "copy_trade"  # Copied from another trader/repo
    HEDGING = "hedging"  # Hedging position (not standalone)

class PositionStatus(Enum):
    """Current status of position"""
    OPENING = "opening"  # Order being placed
    OPEN = "open"  # Active position
    CLOSING = "closing"  # Exit order in progress
    CLOSED = "closed"  # Fully exited
    CANCELLED = "cancelled"  # Never filled
    ERROR = "error"  # Error condition

class SLMode(Enum):
    """Stop loss operational mode"""
    INITIAL = "initial"  # Original SL from entry
    BREAKEVEN = "breakeven"  # Locked at entry price (0% loss)
    MOMENTUM_TRAIL = "momentum_trail"  # Trailing with momentum
    RED_ALERT = "red_alert"  # Aggressive exit when going negative
    MANUAL_OVERRIDE = "manual_override"  # User moved SL manually

@dataclass
class StopLossEvent:
    """Record of SL movement"""
    timestamp: float
    old_sl: float
    new_sl: float
    mode: str
    reason: str
    pnl_at_move: float  # P&L when SL moved
    
@dataclass
class PositionMetrics:
    """Real-time metrics for a position"""
    current_price: float = 0.0
    pnl_usd: float = 0.0
    pnl_percent: float = 0.0
    r_multiple: float = 0.0  # Risk multiples won/lost
    duration_seconds: int = 0
    trade_quality_score: float = 0.0  # 0-100, based on momentum/entry timing
    momentum_efficiency: float = 0.0  # 0-100, how well momentum was captured
    last_update: float = field(default_factory=time.time)

@dataclass
class Position:
    """Universal position record"""
    # Identity
    position_id: str  # Unique ID
    symbol: str  # EUR_USD, BTC_USD, etc
    source: PositionSource  # Where it came from
    
    # Entry Details
    entry_time: float  # Unix timestamp
    entry_price: float
    size_units: float  # Units/lots
    notional_amount: float  # USD equivalent at entry
    
    # SL & TP
    initial_sl: float
    current_sl: float  # May change if SL moved
    take_profit: float
    sl_mode: SLMode  # Current SL mode
    sl_events: List[StopLossEvent] = field(default_factory=list)  # History of SL moves
    
    # Status & Management
    status: PositionStatus = PositionStatus.OPENING
    is_auto_managed: bool = True  # Can system modify SL/TP?
    manual_override_until: float = 0.0  # Timestamp when manual override ends (0=never)
    
    # Metadata
    entry_strategy: str = ""  # Strategy that entered (e.g., "bullish_wolf")
    entry_signal_confidence: float = 0.0  # 0-100
    associated_repo: str = "local"  # Which clone (local, clone_1, clone_2, etc)
    
    # Real-time Metrics
    metrics: PositionMetrics = field(default_factory=PositionMetrics)
    
    # Tracking
    created_at: float = field(default_factory=time.time)
    last_managed_at: float = field(default_factory=time.time)
    close_time: float = 0.0  # When closed (0=still open)
    close_price: float = 0.0
    close_reason: str = ""  # Why it closed
    
    def to_dict(self):
        """Convert to JSON-serializable dict"""
        d = asdict(self)
        d['source'] = self.source.value
        d['status'] = self.status.value
        d['sl_mode'] = self.sl_mode.value
        d['sl_events'] = [
            {
                'timestamp': e.timestamp,
                'old_sl': e.old_sl,
                'new_sl': e.new_sl,
                'mode': e.mode,
                'reason': e.reason,
                'pnl_at_move': e.pnl_at_move,
            }
            for e in d['sl_events']
        ]
        d['metrics'] = asdict(d['metrics'])
        return d

class UniversalPositionRegistry:
    """
    Unified registry for ALL positions across system.
    - Autonomous positions
    - Manual prompt-based positions
    - Webhook positions
    - Copy-trade positions
    
    Features:
    - Real-time tracking
    - Cross-repo awareness
    - Aggressive SL management
    - Portfolio coordination
    """
    
    def __init__(self, data_dir: str = "portfolio_registry"):
        self.data_dir = Path(data_dir)
        self.data_dir.mkdir(exist_ok=True)
        
        self.positions: Dict[str, Position] = {}  # position_id -> Position
        self.lock = threading.RLock()
        
        # Load persisted positions on startup
        self._load_persisted()
        
    def open_position(
        self,
        symbol: str,
        entry_price: float,
        size_units: float,
        initial_sl: float,
        take_profit: float,
        source: PositionSource,
        **metadata
    ) -> str:
        """
        Register a NEW position (any source).
        Returns: position_id
        """
        with self.lock:
            position_id = self._generate_id(symbol, entry_price)
            
            position = Position(
                position_id=position_id,
                symbol=symbol,
                source=source,
                entry_time=time.time(),
                entry_price=entry_price,
                size_units=size_units,
                notional_amount=entry_price * size_units,
                initial_sl=initial_sl,
                current_sl=initial_sl,
                take_profit=take_profit,
                sl_mode=SLMode.INITIAL,
                entry_strategy=metadata.get('entry_strategy', ''),
                entry_signal_confidence=metadata.get('entry_signal_confidence', 0.0),
                associated_repo=metadata.get('associated_repo', 'local'),
                status=PositionStatus.OPENING,
                is_auto_managed=metadata.get('is_auto_managed', True),
            )
            
            self.positions[position_id] = position
            
            # Persist immediately
            self._persist_position(position)
            
            print(f"✅ Position Registered: {position_id} {symbol} @ {entry_price} "
                  f"({size_units} units, SL={initial_sl}, TP={take_profit})")
            
            return position_id
    
    def update_position_metrics(
        self,
        position_id: str,
        current_price: float,
        pnl_usd: float,
        pnl_percent: float,
        r_multiple: float = 0.0,
        trade_quality_score: float = 0.0,
        momentum_efficiency: float = 0.0,
    ) -> Optional[Position]:
        """Update current metrics for a position"""
        with self.lock:
            if position_id not in self.positions:
                return None
            
            pos = self.positions[position_id]
            pos.metrics = PositionMetrics(
                current_price=current_price,
                pnl_usd=pnl_usd,
                pnl_percent=pnl_percent,
                r_multiple=r_multiple,
                duration_seconds=int(time.time() - pos.entry_time),
                trade_quality_score=trade_quality_score,
                momentum_efficiency=momentum_efficiency,
                last_update=time.time(),
            )
            
            # Check for RED ALERT: Going negative immediately
            if pnl_usd < 0 and pnl_percent < -0.3:  # -0.3% loss
                self._trigger_red_alert(position_id)
            
            pos.last_managed_at = time.time()
            self._persist_position(pos)
            
            return pos
    
    def move_stop_loss(
        self,
        position_id: str,
        new_sl: float,
        mode: SLMode,
        reason: str,
    ) -> bool:
        """Move SL for a position with logging"""
        with self.lock:
            if position_id not in self.positions:
                return False
            
            pos = self.positions[position_id]
            
            # Don't move SL if under manual override
            if pos.manual_override_until > time.time():
                return False
            
            old_sl = pos.current_sl
            pos.current_sl = new_sl
            pos.sl_mode = mode
            
            # Log the move
            event = StopLossEvent(
                timestamp=time.time(),
                old_sl=old_sl,
                new_sl=new_sl,
                mode=mode.value,
                reason=reason,
                pnl_at_move=pos.metrics.pnl_usd,
            )
            pos.sl_events.append(event)
            
            if len(pos.sl_events) % 5 == 0:  # Print every 5th move
                print(f"🎯 SL Move [{mode.value}]: {pos.symbol} {old_sl}→{new_sl} "
                      f"({reason}, P&L={pos.metrics.pnl_usd:.2f})")
            
            self._persist_position(pos)
            return True
    
    def close_position(
        self,
        position_id: str,
        close_price: float,
        close_reason: str,
    ) -> bool:
        """Close a position"""
        with self.lock:
            if position_id not in self.positions:
                return False
            
            pos = self.positions[position_id]
            pos.status = PositionStatus.CLOSED
            pos.close_time = time.time()
            pos.close_price = close_price
            pos.close_reason = close_reason
            
            closed_pnl = (close_price - pos.entry_price) * pos.size_units
            
            print(f"✅ Closed: {pos.position_id} {pos.symbol} "
                  f"@ {close_price} | P&L=${closed_pnl:.2f} ({close_reason})")
            
            self._persist_position(pos)
            return True
    
    def set_manual_override(
        self,
        position_id: str,
        duration_seconds: int,
    ) -> bool:
        """User wants to manually control SL for this position"""
        with self.lock:
            if position_id not in self.positions:
                return False
            
            pos = self.positions[position_id]
            pos.is_auto_managed = False
            pos.manual_override_until = time.time() + duration_seconds
            pos.sl_mode = SLMode.MANUAL_OVERRIDE
            
            self._persist_position(pos)
            print(f"🚨 Manual Override: {position_id} for {duration_seconds}s")
            return True
    
    def get_all_open_positions(self) -> List[Position]:
        """Get ALL open positions regardless of source"""
        with self.lock:
            return [p for p in self.positions.values() 
                    if p.status == PositionStatus.OPEN]
    
    def get_positions_by_source(self, source: PositionSource) -> List[Position]:
        """Get all positions from a specific source (AUTONOMOUS vs MANUAL_PROMPT, etc)"""
        with self.lock:
            return [p for p in self.positions.values() if p.source == source and p.status == PositionStatus.OPEN]
    
    def get_positions_by_repo(self, repo: str) -> List[Position]:
        """Get all positions from a specific repo clone"""
        with self.lock:
            return [p for p in self.positions.values() if p.associated_repo == repo and p.status == PositionStatus.OPEN]
    
    def get_portfolio_summary(self) -> Dict:
        """Real-time portfolio status across ALL positions"""
        with self.lock:
            open_pos = self.get_all_open_positions()
            
            total_notional = sum(p.notional_amount for p in open_pos)
            total_pnl = sum(p.metrics.pnl_usd for p in open_pos)
            avg_pnl_percent = sum(p.metrics.pnl_percent for p in open_pos) / len(open_pos) if open_pos else 0.0
            
            auto_positions = self.get_positions_by_source(PositionSource.AUTONOMOUS)
            manual_positions = self.get_positions_by_source(PositionSource.MANUAL_PROMPT)
            
            return {
                'timestamp': time.time(),
                'total_open_positions': len(open_pos),
                'autonomous_positions': len(auto_positions),
                'manual_positions': len(manual_positions),
                'total_notional': total_notional,
                'total_pnl_usd': total_pnl,
                'avg_pnl_percent': avg_pnl_percent,
                'positions_in_red': len([p for p in open_pos if p.metrics.pnl_usd < 0]),
                'positions_in_green': len([p for p in open_pos if p.metrics.pnl_usd > 0]),
                'avg_trade_duration_min': sum(p.metrics.duration_seconds for p in open_pos) / len(open_pos) / 60 if open_pos else 0.0,
            }
    
    def get_position_by_id(self, position_id: str) -> Optional[Position]:
        """Get a specific position"""
        return self.positions.get(position_id)
    
    def _trigger_red_alert(self, position_id: str):
        """Position going negative - trigger aggressive exit"""
        pos = self.positions[position_id]
        
        # Move SL to a very tight level (close to current price)
        aggressive_sl = pos.metrics.current_price + 0.1  # 0.1 pip above current
        
        self.move_stop_loss(
            position_id,
            aggressive_sl,
            SLMode.RED_ALERT,
            f"🚨 RED ALERT: Trade negative {pos.metrics.pnl_percent:.2f}% - aggressive exit"
        )
    
    def _generate_id(self, symbol: str, entry_price: float) -> str:
        """Generate unique position ID"""
        unique_str = f"{symbol}_{entry_price}_{time.time()}_{int(time.time()*1000) % 10000}"
        return hashlib.md5(unique_str.encode()).hexdigest()[:12]
    
    def _persist_position(self, position: Position):
        """Save position to disk"""
        file_path = self.data_dir / f"{position.position_id}.json"
        with open(file_path, 'w') as f:
            json.dump(position.to_dict(), f, indent=2)
    
    def _load_persisted(self):
        """Load all persisted positions on startup"""
        for file_path in self.data_dir.glob("*.json"):
            try:
                with open(file_path) as f:
                    data = json.load(f)
                    # Reconstruct Position object
                    data['source'] = PositionSource(data['source'])
                    data['status'] = PositionStatus(data['status'])
                    data['sl_mode'] = SLMode(data['sl_mode'])
                    data['sl_events'] = [StopLossEvent(**e) for e in data.get('sl_events', [])]
                    data['metrics'] = PositionMetrics(**data.get('metrics', {}))
                    
                    pos = Position(**data)
                    self.positions[pos.position_id] = pos
            except Exception as e:
                print(f"⚠️  Failed to load {file_path}: {e}")
    
    def export_portfolio_json(self, filepath: str = None):
        """Export all positions to JSON for cross-repo sync"""
        if not filepath:
            filepath = self.data_dir / f"portfolio_snapshot_{int(time.time())}.json"
        
        with self.lock:
            data = {
                'timestamp': time.time(),
                'positions': [p.to_dict() for p in self.positions.values()],
                'summary': self.get_portfolio_summary(),
            }
        
        with open(filepath, 'w') as f:
            json.dump(data, f, indent=2)
        
        print(f"💾 Portfolio exported: {filepath}")
        return filepath
    
    def import_portfolio_json(self, filepath: str):
        """Import positions from another repo clone (for sync)"""
        with open(filepath) as f:
            data = json.load(f)
        
        imported_count = 0
        for pos_data in data.get('positions', []):
            pos_id = pos_data['position_id']
            if pos_id not in self.positions:
                # New position from another clone
                pos_data['source'] = PositionSource(pos_data['source'])
                pos_data['status'] = PositionStatus(pos_data['status'])
                pos_data['sl_mode'] = SLMode(pos_data['sl_mode'])
                pos_data['sl_events'] = [StopLossEvent(**e) for e in pos_data.get('sl_events', [])]
                pos_data['metrics'] = PositionMetrics(**pos_data.get('metrics', {}))
                
                pos = Position(**pos_data)
                self.positions[pos_id] = pos
                self._persist_position(pos)
                imported_count += 1
        
        print(f"📥 Portfolio imported: {imported_count} new positions from {filepath}")


# Global instance
_registry = None

def get_registry(data_dir: str = "portfolio_registry") -> UniversalPositionRegistry:
    """Get or create global registry"""
    global _registry
    if _registry is None:
        _registry = UniversalPositionRegistry(data_dir)
    return _registry
